//! Integration test: ingest the real RAG corpus into an in-memory store and retrieve.
//!
//! Uses `../build/rag_corpus.jsonl` (the 927-passage corpus generated by
//! `build_training_jsonl.py`). Skips gracefully if the file is absent so the test suite
//! still runs on a fresh checkout that hasn't built the corpus.

use std::path::PathBuf;

use jesus_twin_store::{Store, SurrealStore};

/// Locate `build/rag_corpus.jsonl` relative to the repo root (two levels up from the crate).
fn corpus_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../build/rag_corpus.jsonl")
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from("../../../build/rag_corpus.jsonl"))
}

#[tokio::test]
async fn ingests_corpus_and_retrieves_by_keyword() {
    let path = corpus_path();
    if !path.exists() {
        eprintln!(
            "skipping: corpus not found at {} (run build_training_jsonl.py)",
            path.display()
        );
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");

    let count = store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest corpus");
    assert_eq!(count, 927, "expected the full red-letter corpus");

    // A keyword that appears in the sayings. BM25 should surface matching passages, each
    // carrying its citation `ref` (the grounding invariant).
    let results = store.retrieve("righteousness", 5).await.expect("retrieve");
    assert!(
        !results.passages.is_empty(),
        "expected at least one match for 'righteousness'"
    );
    for p in &results.passages {
        assert!(
            !p.ref_.is_empty(),
            "every retrieved passage must carry a citation ref"
        );
        assert!(p.score.is_some(), "BM25 retrieve must populate a score");
    }
}

#[tokio::test]
async fn multi_word_query_matches_any_term() {
    // Regression: the default `@n@` operator is AND-only, so multi-word queries returned
    // nothing even when terms were present. Retrieval uses `@n,OR@` so a query matching ANY
    // term surfaces the passage. "Caesar" appears verbatim in the corpus.
    let path = corpus_path();
    if !path.exists() {
        eprintln!("skipping: corpus not found at {}", path.display());
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");
    store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest");

    let results = store
        .retrieve("render to Caesar", 5)
        .await
        .expect("retrieve");
    assert!(
        results
            .passages
            .iter()
            .any(|p| p.text_original.contains("Caesar")),
        "multi-word query should surface the Caesar saying via OR matching"
    );
}

#[tokio::test]
async fn retrieve_returns_empty_for_out_of_corpus_query() {
    let path = corpus_path();
    if !path.exists() {
        eprintln!("skipping: corpus not found at {}", path.display());
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");
    store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest");

    // A term with no coverage in first-century sayings -> empty set -> the coverage gate
    // will refuse (the historically-humble stance; training_data_spec.md §5).
    let results = store.retrieve("cryptocurrency", 5).await.expect("retrieve");
    assert!(
        results.passages.is_empty(),
        "out-of-corpus query should match nothing"
    );
    assert_eq!(results.top_score(), 0.0);
}
