//! Integration test: ingest the real RAG corpus into an in-memory store and retrieve.
//!
//! Uses `../build/rag_corpus.jsonl` (the 927-passage corpus generated by
//! `build_training_jsonl.py`). Skips gracefully if the file is absent so the test suite
//! still runs on a fresh checkout that hasn't built the corpus.

use std::path::PathBuf;

use jesus_twin_store::{Store, SurrealStore};

/// Locate `build/rag_corpus.jsonl` relative to the repo root (two levels up from the crate).
fn corpus_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../build/rag_corpus.jsonl")
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from("../../../build/rag_corpus.jsonl"))
}

#[tokio::test]
async fn ingests_corpus_and_retrieves_by_keyword() {
    let path = corpus_path();
    if !path.exists() {
        eprintln!(
            "skipping: corpus not found at {} (run build_training_jsonl.py)",
            path.display()
        );
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");

    let count = store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest corpus");
    assert_eq!(count, 927, "expected the full red-letter corpus");

    // A keyword that appears in the sayings. BM25 should surface matching passages, each
    // carrying its citation `ref` (the grounding invariant).
    let results = store.retrieve("righteousness", 5).await.expect("retrieve");
    assert!(
        !results.passages.is_empty(),
        "expected at least one match for 'righteousness'"
    );
    for p in &results.passages {
        assert!(
            !p.ref_.is_empty(),
            "every retrieved passage must carry a citation ref"
        );
        assert!(p.score.is_some(), "BM25 retrieve must populate a score");
    }
}

#[tokio::test]
async fn multi_word_query_matches_any_term() {
    // Regression: the default `@n@` operator is AND-only, so multi-word queries returned
    // nothing even when terms were present. Retrieval uses `@n,OR@` so a query matching ANY
    // term surfaces the passage. "Caesar" appears verbatim in the corpus.
    let path = corpus_path();
    if !path.exists() {
        eprintln!("skipping: corpus not found at {}", path.display());
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");
    store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest");

    let results = store
        .retrieve("render to Caesar", 5)
        .await
        .expect("retrieve");
    assert!(
        results
            .passages
            .iter()
            .any(|p| p.text_original.contains("Caesar")),
        "multi-word query should surface the Caesar saying via OR matching"
    );
}

#[tokio::test]
async fn retrieve_returns_empty_for_out_of_corpus_query() {
    let path = corpus_path();
    if !path.exists() {
        eprintln!("skipping: corpus not found at {}", path.display());
        return;
    }

    let store = SurrealStore::memory().await.expect("open in-memory store");
    store
        .ingest_corpus(path.to_str().unwrap())
        .await
        .expect("ingest");

    // A term with no coverage in first-century sayings -> empty set -> the coverage gate
    // will refuse (the historically-humble stance; training_data_spec.md §5).
    let results = store.retrieve("cryptocurrency", 5).await.expect("retrieve");
    assert!(
        results.passages.is_empty(),
        "out-of-corpus query should match nothing"
    );
    assert_eq!(results.top_score(), 0.0);
}

/// hebrew-bible: the Tanakh loads into its OWN table and retrieves as labeled source material
/// (BM25-only here — no embedder). It must NOT leak into the red-letter `saying` retrieval.
#[tokio::test]
async fn ingests_tanakh_as_separate_source_corpus() {
    use std::io::Write;

    let store = SurrealStore::memory().await.expect("open in-memory store");
    let path = std::env::temp_dir().join(format!("tanakh-test-{}.jsonl", std::process::id()));
    {
        let mut f = std::fs::File::create(&path).expect("temp jsonl");
        writeln!(
            f,
            r#"{{"ref":"Genesis 1:1","text":"In the beginning God created the heaven and the earth.","book":"Genesis","category":"torah","translation":"JPS 1917"}}"#
        )
        .unwrap();
        writeln!(
            f,
            r#"{{"ref":"Deuteronomy 8:3","text":"man doth not live by bread only, but by every thing that proceedeth out of the mouth of the LORD.","book":"Deuteronomy","category":"torah","translation":"JPS 1917"}}"#
        )
        .unwrap();
    }

    let n = store
        .ingest_tanakh(path.to_str().unwrap())
        .await
        .expect("ingest tanakh");
    assert_eq!(n, 2, "two verses loaded");

    let hits = store
        .retrieve_tanakh("bread", 5)
        .await
        .expect("retrieve tanakh");
    assert!(
        hits.iter().any(|p| p.ref_ == "Deuteronomy 8:3"),
        "BM25 should surface the bread verse, got {:?}",
        hits.iter().map(|p| &p.ref_).collect::<Vec<_>>()
    );
    assert!(
        hits.iter().all(|p| p.translation == "JPS 1917"),
        "every Tanakh result is labeled JPS 1917 source material"
    );

    // Separation: the red-letter `saying` retrieval must not return Tanakh verses.
    let saying_hits = store.retrieve("bread", 5).await.expect("retrieve saying");
    assert!(
        saying_hits.passages.is_empty(),
        "Tanakh must not leak into the red-letter saying corpus"
    );

    let _ = std::fs::remove_file(&path);
}
